version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: housedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redispassword
    volumes:
      - cache:/data

volumes:
  postgres_data:
  cache: