version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: housedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: